CREATE TABLE `wx_game_analysis_data` (
  `id` int NOT NULL AUTO_INCREMENT,
  `app_id` varchar(18) CHARACTER SET utf8mb3 COLLATE utf8mb3_general_ci NOT NULL,
  `date` date NOT NULL,
  `active_num` int DEFAULT NULL COMMENT '活跃用户数',
  `active_times` int DEFAULT NULL COMMENT '活跃用户访问次数（前端不显示）',
  `active_average_times` double(5,2) DEFAULT NULL COMMENT '活跃用户人均访问次数（前端不显示）= 活跃用户访问次数 / 活跃用户数',
  `active_average_duration` int DEFAULT NULL COMMENT '活跃用户平均停留时长（秒）',
  `active_secondary_retention_rate` double(5,4) DEFAULT NULL COMMENT '活跃用户次留',
  `new_num` int DEFAULT NULL COMMENT '新增用户数',
  `new_secondary_retention_rate` double(5,4) DEFAULT NULL COMMENT '新增用户次留',
  `share_num` int DEFAULT NULL COMMENT '分享用户数（前端不显示）',
  `share_times` int DEFAULT NULL COMMENT '分享次数（前端不显示）',
  `share_average_times` double(5,2) DEFAULT NULL COMMENT '人均分享次数（前端不显示） = 分享次数 / 分享用户数',
  `share_rate` double(5,4) DEFAULT NULL COMMENT '分享率（前端不显示） = 分享用户数 / 活跃用户数',
  `income` int DEFAULT NULL COMMENT '广告收入，需除以100',
  `search` int DEFAULT NULL COMMENT '搜索来源用户(活跃)',
  `search_new` int DEFAULT NULL COMMENT '搜索来源用户(新增)',
  `ad` int DEFAULT NULL COMMENT '广告来源用户(活跃)',
  `ad_new` int DEFAULT NULL COMMENT '广告来源用户(新增)',
  `put_on` int unsigned DEFAULT '1' COMMENT '标记是否是投放的游戏，1表示不是，2表示是（已废弃）',
  `price` double(13,2) DEFAULT '0.00' COMMENT '广告金收入',
  `first_day_price` double(13,2) DEFAULT '0.00' COMMENT '首日广告金',
  `wx_cost` double(13,2) DEFAULT '0.00' COMMENT '微信消耗，从腾讯广告获取',
  `roi1` double(7,4) DEFAULT '0.0000' COMMENT '首日roi，从腾讯广告获取',
  `new_from_wxad` int DEFAULT '0' COMMENT '注册来源-微信广告',
  `new_from_app` int DEFAULT '0' COMMENT '注册来源-外部应用',
  `new_from_search` int DEFAULT '0' COMMENT '注册来源-搜索',
  `new_from_chat` int DEFAULT '0' COMMENT '注册来源-会话',
  PRIMARY KEY (`id`) USING BTREE,
  KEY `app_id` (`app_id`) USING BTREE,
  KEY `date` (`date`) USING BTREE,
  KEY `app_id-date` (`app_id`,`date` DESC) USING BTREE
) ENGINE=InnoDB AUTO_INCREMENT=342769 DEFAULT CHARSET=utf8mb3;